baseURL = "https://mitjanemec.github.io/fireball-slovenia-site/"
title = "Fireball Slovenija"
theme = "blowfish"
defaultContentLanguage = "sl"
enableRobotsTXT = true
summaryLength = 0

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[imaging]
  anchor = "Center"
