[[main]]
  name = "Novice"
  pageRef = "news"
  weight = 10

[[main]]
  name = "Jadrnica"
  identifier = "sailing-class-info"
  weight = 20

[[main]]
  name = "Fireball se predstavi"
  parent = "sailing-class-info"
  pageRef = "sailing-class-information/fireball-se-predstavi"
  weight = 20

[[main]]
  name = "Pravila razreda"
  parent = "sailing-class-info"
  pageRef = "sailing-class-information/class-rules"
  weight = 21

[[main]]
  name = "ABC jadranja"
  parent = "sailing-class-info"
  pageRef = "sailing-class-information/abc-jadranja"
  weight = 22

[[main]]
  name = "Tekmovanja"
  identifier = "competitions"
  weight = 30

[[main]]
  name = "Koledar tekoče sezone"
  parent = "competitions"
  pageRef = "competitions/current-season-calendar"
  weight = 31

[[main]]
  name = "Rezultati tekoče sezone"
  parent = "competitions"
  pageRef = "competitions/current-season-results"
  weight = 32

[[main]]
  name = "Pravila slovenskega pokala"
  parent = "competitions"
  pageRef = "competitions/pravila-slovenskega-pokala"
  weight = 33

[[main]]
  name = "Rezultati preteklih sezon"
  identifier = "past-season-results"
  parent = "competitions"
  pageRef = "competitions/past-season-results"
  weight = 34

[[main]]
  name = "Posamezne regate"
  parent = "past-season-results"
  pageRef = "competitions/past-season-results/separate-regattas"
  weight = 35

[[main]]
  name = "Skupna sezona"
  parent = "past-season-results"
  pageRef = "competitions/past-season-results/overall-season"
  weight = 36

[[main]]
  name = "Informacije o klubu"
  pageRef = "club-information"
  weight = 40

[[main]]
  name = "Zunanje povezave"
  pageRef = "external-links"
  weight = 50

[[main]]
  name = "Media"
  identifier = "media"
  weight = 60

[[main]]
  name = "Foto"
  parent = "media"
  pageRef = "media/foto"
  weight = 61
